DROP TABLE IF EXISTS NOTE CASCADE;
DROP TABLE IF EXISTS ELEVE CASCADE;
DROP TABLE IF EXISTS MATIERE CASCADE;
DROP TABLE IF EXISTS ECOLE CASCADE;

CREATE TABLE ECOLE (
    numEcole SERIAL PRIMARY KEY,
    design VARCHAR(100) NOT NULL,
    adresse VARCHAR(150)
);

CREATE TABLE MATIERE (
    numMat SERIAL PRIMARY KEY,
    designMat VARCHAR(100) NOT NULL,
    coef INT NOT NULL DEFAULT 2
);

CREATE TABLE ELEVE (
    numEleve SERIAL PRIMARY KEY,
    numEcole INT NOT NULL REFERENCES ECOLE(numEcole) ON DELETE CASCADE,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100),
    dateNaissance DATE NOT NULL
);

CREATE TABLE NOTE (
    anneeScolaire VARCHAR(9) NOT NULL,
    numEleve INT NOT NULL REFERENCES ELEVE(numEleve) ON DELETE CASCADE,
    numMat INT NOT NULL REFERENCES MATIERE(numMat) ON DELETE CASCADE,
    note NUMERIC(4,2) CHECK (note >= 0 AND note <= 20),
    PRIMARY KEY (anneeScolaire, numEleve, numMat)
); 